<h1>Ajouter catégorie</h1>
<form method="POST" class="" enctype="multipart/form-data">
    <div class="add_categorie">
        <div class="cat_titre">
        <label>Titre</label>
            <input type="text" class="input__titre" name="titre">
        </div>
        <div class="cat_titre">
        <label>Image</label>
            <input type="file" class="input__image" name="image">
        </div>
        <button type="submit" name="ajouter" class="btn_ajouter">Ajouter</button>
    </div>
</form>