<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=<device-width>, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link type="text/css" rel="normalize" href="normalize.css"/>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/stylesheet.css" type="text/css" />
	<title>Admin</title>
</head>
<body>
	<header class="header" id="scrollHeader">
		<div class="slidebar">
		    <?php if(isset($_SESSION['Admin'])){?>
			<a class="slidebar__a" href="index.php"><h1 class="slidebar__h1">MyAdmin</h1></a>
			<?php } else{?>
				<h1 class="slidebar__h1">MyAdmin</h1>
			<?php }?>

			<?php if(isset($_SESSION['Admin'])){?>
			<div class="admin__logedin">
		        <div class="adminphoto__circle"><i class="fa fa-user"></i></div>
				<div class="admin__name"><?php echo $_SESSION['Admin']; ?><i class="fa fa-chevron-down"></i>
					<div class="down__content">
                        <a class="down__a" href="signout.php">Sign out</a>
					</div>
			    </div>
		    </div>
			<?php } ?>
	    </div>
	</header>
	<?php if(isset($_SESSION['Admin'])){?>
	<div class="menu">
			<p class="menu__p">Catégories</p>
			<a class="menu__a" href="categories.php">Liste des Catégories</a>
			<a class="menu__a" href="ajouter_categorie.php">Ajouter une Catégorie</a>
			<p class="menu__p">Playlists</p>
			<a class="menu__a" href="audios.php">Audios</a>
			<a class="menu__a" href="ajouter_audio.php">Ajouter audio</a>
			<p class="menu__p">Comments</p>
			<a class="menu__a" href="comments.php">Liste des comments</a>
		</div>
		<?php }?>
<main class="container main__accueil"> 
	<?php include 'Templates/'.$template.'.phtml' ?>
</main>
	<footer class="footer">
         <div class="footer__div">Copyright © 2020. All rights reserved.</div>
	</footer>
	<script src="../js/header.js"></script>
</body>
</html>