<div>
    <?php echo $msg; ?>
</div>
<form method="POST" class="login__form">
    <div class="login__div">
        <label>Username</label>
        <input type="text" placeholder="Enter Username" name="user" class="input_user" required>
        <label >Password</label>
        <input type="password" placeholder="Enter Password" name="password" class="input_password" required>
        <button type="submit" name="login" class="login__button">Login</button>
    </div>
</form>