<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link type="text/css" rel="normalize" href="normalize.css"/>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/style.css" type="text/css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<title>Muzik</title>
</head>
<body class="body">

<header class="header">
	<nav class="nav__connexion">
		<?php if(!isset($_SESSION['user'])){?>
			<a class="nav__a" href="./connexion">Connexion</a>
			<a class="nav__a" href="./inscription">Inscription</a>
		<?php }else{ ?>
			<a class="nav__a" href="">Bonjour <?= $_SESSION['user'] ?></a>
			<a class="nav__a" href="./logout">Déconnexion</a>
			<?php } ?>
	</nav>
	
	<nav class="header__nav  container">
		<a  class="logo" href="./accueil"><img class="header__logo" src="images/logo.png" alt="logo"></a>
		<div id="menuDiv" class="menu">
        <a href="javascript:void(0)" class="closebutton" onclick="closeMenu()"><i class="fa fa-bars"></i></a>
		<a class="header__a" href="./accueil"><i class="header__i fa fa-home"></i>Accueil</a>
		<a class="header__a" href="./playlist"><i class="header__i fa fa-music"></i>Playlists</a>
		<a class="header__a" href="./blogs"><i class="header__i fa fa-folder"></i>Blog</a>
		<a class="header__a" href="./contact"><i class="header__i fa fa-envelope"></i>Contact</a>
		</div>
		<span class="menuOpen"  onclick="openMenu()"><i class="fa fa-bars"></i></span>
	</nav>
</header>

    <div>
		<?php include 'Templates/'.$template.'.phtml' ?>
	</div>
	
	<footer class="footer">
		<div class="footer__div">
		    <p class="footer__p">Suivez-nous sur</p>
		    <a href="#"><i class="fa footer__fa fa-facebook"></i></a>
		    <a href="#"><i class="fa footer__fa fa-twitter"></i></a>
            <a href="."><i class="fa footer__fa fa-instagram"></i></a>
		    <p class="footer__p">Copyright © 2020 Muzik. All rights reserved.</p>
	    </div>
	</footer>
	<script src="js/slider.js"></script>
	<script src="js/player.js"></script>
	<script src="js/mobileMenu.js"></script>
	<script src="js/comments.js"></script>	
</body>
</html>