<!--Main-->
	<main class="container">
	<h1 class="login__h1"><i class="fa login__fa fa-chevron-right"></i>Login</h1>
	    <form method="POST" class="login__form" >                                        
		    <ul class="login__ul">
			    <li class="login__li">
				    <label class="login__label">Adresse Email</label>
				    <input required type="text" class="login__input" name="Email">
			    </li>
			    <li class="login__li">
				    <label class="login__label">Mot De Passe</label>
				    <input required type="password" class="login__input" name="Pass">
				</li>
			</ul>
		    <div class="">
			    <button class="login__button" type="submit"  name="ajouter">Login</button>
		    </div>
	    </form>
	</main>
	

