<!--Main-->
<main class="container">
	<h1 class="playlist__h1">Playlists</h1>
	<div class="main__playlist">
		<?php foreach($cats as $cat): ?> 
			<div class="playlist__div">
		<?php if(!isset($_SESSION['user'])){?>
			<a class="playlist__a" href="./inscription">
			    <img class="playlist__image" src="<?php echo $cat['Image']?>" alt="">	
			    <h2 class="playlist__h2"><?php echo $cat['Titre']?></h2>
			</a>
		<?php }else{ ?>
			<a class="playlist__a" href="music-<?php echo get_url_text($cat['Titre'])?>-<?php echo $cat['Id']?>">
			    <img class="playlist__image" src="<?php echo $cat['Image']?>" alt="">	
			    <h2 class="playlist__p"><?php echo $cat['Titre']?></h2>
			</a>
        <?php } ?>
			</div>
		<?php endforeach;?>	
	</div>
</main>
