<!--Main-->
	<main class="container">
		<h1 class="login__h1"><i class="fa login__fa fa-chevron-right"></i>Inscription</h1>
	    <form method="POST" class="login__form" >                                        
		    <ul class="login__ul">
			    <li class="login__li">
				    <label class="login__label">Nom</label>
				    <input required type="text" class="login__input" name="Nom">
			    </li>
			    <li class="login__li">
				    <label class="login__label">Prénom</label>
				    <input required type="text" class="login__input" name="Prenom">
			    </li>
			    <li class="login__li">
				    <label class="login__label">Adresse Email</label>
				    <input required type="email" class="login__input" name="Email">
			    </li>
			    <li class="login__li">
				    <label class="login__label">Mot De Passe</label>
				    <input required type="password" class="login__input" name="Pass">
			    </li>
		    </ul>
			<button class="login__button" type="submit"  name="ajouter">Creez votre compte</button>
		</form>
    </main>
	